### Feature Shipment — GET ALL / GET ONE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticacion)
@baseUrl = http://localhost:4000
@id = 1

# @name getAllShipment
GET {{baseUrl}}/api/shipments

###

# @name getOneShipment
GET {{baseUrl}}/api/shipments/{{id}}
