### Feature Package — CREATE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticacion)
@baseUrl = http://localhost:4000

# @name createPackage
POST {{baseUrl}}/api/packages
Content-Type: application/json

{
  "envio_id": 1,
  "descripcion_contenido": "Contenido del paquete",
  "peso_kg": 10.5,
  "alto_cm": 10.5,
  "ancho_cm": 10.5,
  "largo_cm": 10.5,
  "valor_declarado": 50000,
  "es_fragil": true,
  "is_active": true
}
