### Feature Invoice — GET ALL / GET ONE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticacion)
@baseUrl = http://localhost:4000
@id = 1

# @name getAllInvoice
GET {{baseUrl}}/api/invoices

###

# @name getOneInvoice
GET {{baseUrl}}/api/invoices/{{id}}
